# Generated by Django 5.1.6 on 2026-06-09 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=65535)),
                ('connected_users', models.ManyToManyField(related_name='connected_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
