# Generated by Django 5.1.6 on 2026-06-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0002_chatbox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatbox',
        ),
    ]
