# Generated by Django 5.1.6 on 2025-02-25 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('priority', models.IntegerField(unique=True)),
                ('description', models.TextField()),
                ('is_staff_group', models.BooleanField(default=False)),
                ('minimum_messages', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('messages_count', models.IntegerField(default=0)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('loisirs', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField()),
                ('type', models.CharField(choices=[('pacifist', 'Pacifiste'), ('neutral', 'Neutre'), ('genocide', 'Génocidaire')], default='neutral', max_length=20)),
                ('favorite_games', models.CharField(blank=True, max_length=255, null=True)),
                ('zodiac_sign', models.CharField(choices=[('capricorne', 'Capricorne (22déc-19jan)'), ('verseau', 'Verseau (20jan-19fev)'), ('poissons', 'Poissons(20fev-20mar)'), ('belier', 'Bélier (21mar-19avr)'), ('taureau', 'Taureau(20avr-20mai)'), ('gemeaux', 'Gémeaux (21mai-20juin)'), ('Cancer', 'Cancer (21juin-23juil)'), ('lion', 'Lion (24juil-23aoû)'), ('vierge', 'Vierge (24aoû-22sep)'), ('balance', 'Balance (23sep-22oct)'), ('scorpion', 'Scorpion (23oct-21nov)'), ('sagittaire', 'Sagittaire (22nov-21déc)')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Masculin'), ('female', 'Féminin')], max_length=20)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('skype', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.TextField(blank=True, max_length=65535, null=True)),
                ('groups', models.ManyToManyField(related_name='users', to='forum.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
