# Generated by Django 5.1.6 on 2025-02-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forumgroup_color_forumgroup_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumgroup',
            name='minimum_messages',
            field=models.IntegerField(),
        ),
    ]
