# Generated by Django 5.1.6 on 2025-02-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumgroup',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/group_icons/'),
        ),
    ]
