# Generated by Django 5.1.6 on 2025-02-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_category_post_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='DEFAULT_CATEGORY_NAME', max_length=60),
        ),
    ]
