# Generated by Django 5.1.6 on 2025-02-27 18:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 27, 19, 11, 52, 859104)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.topic'),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='DEFAULT POST TEXT', max_length=65535),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.category'),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 27, 19, 12, 0, 816468)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_announcement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_root_topic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_sub_forum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='last_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_in_topics', to='forum.post'),
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='total_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
