# Generated by Django 5.1.6 on 2025-02-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_post_author_post_created_time_post_post_post_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='topic',
        ),
    ]
