# Generated by Django 5.1.6 on 2025-02-27 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_alter_post_author_alter_post_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='is_root_topic',
        ),
    ]
