# Generated by Django 5.1.6 on 2025-02-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_remove_topic_is_root_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
