# Generated by Django 5.1.6 on 2025-03-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_alter_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='index_topics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='index_topics', to='forum.post'),
        ),
    ]
