# Generated by Django 5.1.6 on 2025-03-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_remove_category_index_topics_category_index_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='index_topics',
            field=models.ManyToManyField(blank=True, related_name='index_topics', to='forum.topic'),
        ),
    ]
