# Generated by Django 5.1.6 on 2025-03-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_category_slug_topic_slug_alter_topic_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_is_public',
            field=models.BooleanField(default=False),
        ),
    ]
