# Generated by Django 5.1.6 on 2025-03-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_profile_email_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='last_message_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
