# Generated by Django 5.1.6 on 2025-03-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0025_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='name',
            field=models.CharField(default='rezsdger', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forum',
            name='announcement_topics',
            field=models.ManyToManyField(blank=True, to='forum.topic'),
        ),
    ]
