# Generated by Django 5.1.6 on 2025-03-02 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0026_forum_name_alter_forum_announcement_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='forum.category'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(default='DEFAULT_TITLE_VALUE', max_length=60),
            preserve_default=False,
        ),
    ]
