# Generated by Django 5.1.6 on 2025-03-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0027_alter_post_topic_alter_topic_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
