# Generated by Django 5.1.6 on 2025-03-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0029_remove_category_is_hidden_alter_post_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
