# Generated by Django 5.1.6 on 2025-03-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0030_category_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='total_children',
            field=models.IntegerField(default=0),
        ),
    ]
