# Generated by Django 5.1.6 on 2025-03-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0031_topic_total_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='total_posts',
            new_name='total_replies',
        ),
    ]
