# Generated by Django 5.1.6 on 2025-03-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0032_rename_total_posts_topic_total_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='last_message_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
