# Generated by Django 5.1.6 on 2025-03-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0035_forum_total_messages_forum_total_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumgroup',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forumgroup',
            name='is_messages_group',
            field=models.BooleanField(default=False),
        ),
    ]
