# Generated by Django 5.1.6 on 2025-03-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0036_forumgroup_is_hidden_forumgroup_is_messages_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='super_topic',
            field=models.ManyToManyField(blank=True, null=True, to='forum.topic'),
        ),
    ]
