# Generated by Django 5.1.6 on 2025-03-12 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0037_topic_super_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='super_topic',
        ),
        migrations.AddField(
            model_name='topic',
            name='super_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_topics', to='forum.topic'),
        ),
    ]
