# Generated by Django 5.1.6 on 2025-03-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0038_remove_topic_super_topic_topic_super_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='super_topic',
        ),
    ]
