# Generated by Django 5.1.6 on 2025-03-14 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0040_profile_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='online_record',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forum',
            name='online_record_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2000, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
