# Generated by Django 5.1.6 on 2025-04-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0044_alter_profile_zodiac_sign'),
        ('precise_bbcode', '0002_alter_bbcodetag_id_alter_smileytag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmileyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('smileys', models.ManyToManyField(blank=True, related_name='categories', to='precise_bbcode.smileytag')),
            ],
        ),
    ]
