# Generated by Django 5.1.6 on 2025-05-24 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0046_poll_polloption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='poll',
            name='can_change_vote',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='forum.topic'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
