# Generated by Django 5.1.6 on 2025-05-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0047_alter_poll_options_poll_can_change_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='can_change_vote',
            field=models.IntegerField(default=1),
        ),
    ]
