# Generated by Django 5.1.6 on 2025-06-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0048_alter_poll_can_change_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upload_size',
            field=models.BigIntegerField(default=0, help_text='Total upload size in bytes. Used for image upload limits.'),
        ),
    ]
