# Generated by Django 5.1.6 on 2025-06-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0050_subforum'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='polloption',
            unique_together=set(),
        ),
    ]
