# Generated by Django 5.1.6 on 2025-07-15 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0051_alter_polloption_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='latest_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_latest_message', to='forum.post'),
        ),
    ]
