# Generated by Django 5.1.6 on 2025-07-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0053_profile_name_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='has_subforum_children',
            field=models.BooleanField(default=False),
        ),
    ]
