# Generated by Django 5.1.6 on 2025-07-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0056_privatemessagethread_privatemessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatemessage',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='privatemessagethread',
            old_name='created_at',
            new_name='created_time',
        ),
    ]
