# Generated by Django 5.1.6 on 2025-08-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0057_rename_created_at_privatemessage_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
