# Generated by Django 5.1.6 on 2025-08-30 10:19

import os
from django.db import migrations
from django.conf import settings
from django.core.files.images import ImageFile
from django.contrib.staticfiles import finders

group_name_to_icon_filename = {
    "Fallen Child": "gicon_fallen_child.png",
    "You're blue now !": "gicon_youre_blue_now.png",
    "Made of Fire": "gicon_made_of_fire.png",
    "Real Spider": "gicon_real_spider.png",
    "It's showtime !": "gicon_its_showtime.png",
    "Hopeful Dreamer": "gicon_hopeful_dreamer.png",
    "Royal Guard Apprentice": "gicon_royal_guard_apprentice.png",
    "Royal Guard": "gicon_royal_guard.png",
    "Determination": "gicon_determination.png",
}

def forwards_func(apps, schema_editor):
    """
    Will be executed when the migration is applied.
    """

    ForumGroup = apps.get_model("forum", "ForumGroup")
    db_alias = schema_editor.connection.alias
    instances = ForumGroup.objects.using(db_alias).all()

    for instance in instances:
        group_name = instance.name
        icon_filename = group_name_to_icon_filename.get(group_name)
        if icon_filename:
            relative_path = os.path.join('images', 'group_icons', icon_filename)
            absolute_image_path = finders.find(relative_path)

            if not absolute_image_path:
                print(f"\n[Warning] Could not find static file for group '{group_name}': '{relative_path}'. Skipping.")
                continue

            with open(absolute_image_path, 'rb') as f:
                image = ImageFile(f, name=icon_filename)
                instance.icon = image
                instance.save()



class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0058_profile_is_hidden'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
