# Generated by Django 5.1.6 on 2025-10-06 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0059_populate_group_icons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
