# Generated by Django 5.1.6 on 2026-05-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0062_chatboxmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatboxMessage',
        ),
    ]
