# Generated by Django 5.1.6 on 2025-06-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='archivepolloption',
            unique_together=set(),
        ),
    ]
