# Generated by Django 5.1.6 on 2025-06-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_alter_archiveprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveprofile',
            name='last_login',
            field=models.DateTimeField(),
        ),
    ]
