# Generated by Django 5.1.6 on 2025-06-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_alter_archiveprofile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivecategory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archivepost',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archivesubforum',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archivetopic',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
