# Generated by Django 5.1.6 on 2025-07-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_archivetopic_latest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveprofile',
            name='name_color',
            field=models.CharField(blank=True, help_text="Color of the user's name in the forum. Use a hex color code starting with #.", max_length=20, null=True),
        ),
    ]
