# Generated by Django 5.1.6 on 2025-06-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_alter_archivecategory_id_alter_archivepost_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveforum',
            name='online_record_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='archiveforumgroup',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='archivepoll',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='archivepost',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='archivepost',
            name='updated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivetopic',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='archivetopic',
            name='last_message_time',
            field=models.DateTimeField(null=True),
        ),
    ]
