# Generated by Django 5.1.6 on 2025-07-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_archiveprofile_name_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivetopic',
            name='has_subforum_children',
            field=models.BooleanField(default=False),
        ),
    ]
