# Generated by Django 5.1.6 on 2025-07-17 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_archivetopic_has_subforum_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveprofile',
            name='top_group',
            field=models.ForeignKey(blank=True, help_text="The top group of the user, used for displaying the user's group name and icon.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_group_users', to='archive.archiveforumgroup'),
        ),
    ]
