# Generated by Django 5.1.6 on 2025-06-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_alter_archiveforum_online_record_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeuser',
            name='username',
            field=models.CharField(blank=True, max_length=15000, null=True),
        ),
    ]
