# Generated by Django 5.1.6 on 2025-06-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_alter_fakeuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivetopic',
            name='moved',
            field=models.BooleanField(default=False),
        ),
    ]
